version: "3.7"

services:
  # Backend API
  smart-brain-api:
    container_name: backend
    # image: node:dubnium # not required as it is going to use build below
    build: ./ # this uses the Dockerfile as the place to build from.
    command: npm run start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: psql postgres://Sally:secret@postgres:5430/smart-brain-docker
    links:
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/smart-brain-api # maps the currect director ./ to the docker-compose directory

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: Sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    image: postgres
    ports:
      - "5430:5432"
